import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {AiFillPlusCircle } from 'react-icons/ai';
import { v4 as uuidv4 } from 'uuid';
import List from "./List";
import useTodo from '@/Hooks/useTodo';
import { ChangeEvent } from 'react';
import { useOnKeyPress } from '../Hooks/useOnKePress';

export default function Home() {
  const { 
    currentItem,
    setCurrentItem,
    items,
    addItem,
    removeItem,
    updateItem 
  } = useTodo();

useOnKeyPress(addItem, 'Enter');

  return (
    <>
      <Head>
        <title>To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-7xl md:text-8xl text-gray-300 mb-6">To Do List</h1>
      <div className="mb-10 shadow-lg border-solid border-1 border-light-blue-500 rounded-full p-4 w-full lg:w-3/6 h-14 flex justify-center items-center">
        <input  type="text" placeholder = "Add todo" className="w-11/12 h-12 border-none outline-none" value = {currentItem.name} onChange={(e: ChangeEvent<HTMLInputElement>) => setCurrentItem({...currentItem, id: uuidv4(), name: e.target.value})}/>
        <AiFillPlusCircle className="text-green-500 text-3xl -ml-4 cursor-pointer" onClick={addItem}/>
        </div>
       <List items = {items} removeItem = { removeItem } updateItem = {updateItem }/>
      </main>
    </>
  )
}
